pre-upload: use first-parent diff for list of affected files
Otherwise, trying to upload a merge can fail with errors like

 ValueError: Failed to parse diff output: ::100644 100644 100644 4d2b33a 4d2b33a d63fea7 MM      BUILD

because "git diff <foo>^!" returns a diff against all parents
that DIFF_RE does not know how to parse.

Reported-by: Matthew Maurer <mmaurer@google.com>
Change-Id: Iafd846f083c0c078b383f7d48ad00cce896a404c